name: pathwise_frontend
    description: A new Flutter project.
    publish_to: 'none'
    version: 1.0.0+1

    environment:
      sdk: '>=3.0.0 &lt;4.0.0'

    dependencies:
      flutter:
        sdk: flutter
      cupertino_icons: ^1.0.2
      http: ^1.2.1
      google_maps_flutter: ^2.5.3
      geolocator: ^10.1.0
      provider: ^6.0.5
      flutter_bloc: ^8.1.3
      socket_io_client: ^2.0.3+1
      flutter_secure_storage: ^9.0.0
      jwt_decoder: ^2.0.1
      flutter_local_notifications: ^16.3.2

    dev_dependencies:
      flutter_test:
        sdk: flutter
      flutter_lints: ^2.0.0

    flutter:
      uses-material-design: true
